### ISSUE TITLE
Make response_model optional

### ISSUE THREAD

**Issue by timconnorz** [instructor-ai/instructor-js#114]
**response_model** is currently not an optional parameter, but it would be nice if it was for cases where its unnecessary.
In this case I expect Instructor would skip over the LLMValidator step.

**Comment by roodboi** [comment]
It should do a straight pass-through if the additional params are not provided - can you share under what circumstances this is not the case?

![CleanShot 2024-02-10 at 15 57 23@2x](https://github.com/instructor-ai/instructor-js/assets/344842/80c4889f-46cc-49bc-ba37-0d9584636bc2)

**Comment by timconnorz** [comment]
Ah my bad, I was confused by the errors I was getting. 

What confused me what the fact that when response_model is specified, you get your response in the exact shape of the model, but when it's omitted, you have to revert back to choices[0].delta and append them to the string yourself.
