### ISSUE TITLE
Debugging is challenging, can I access the entire response?

### ISSUE THREAD

**Issue by gregschwartz** [instructor-ai/instructor-js#129]
Could use some help with debugging functionality. I found the [undocumented?] debug flag, and that helped a little. But now I'm getting Zod errors like this:
````
[Instructor:ERROR] 2024-02-29T01:48:45.045Z: IdeaArray Error:  Validation error: Required at "ideas[11].catchyYoutubeTitle"
/Users/greg/code/aurite-consulting-client/bird-apps/node_modules/.pnpm/zod@3.22.4/node_modules/zod/lib/types.js:43
                const error = new ZodError_1.ZodError(ctx.common.issues);
                              ^

ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "ideas",
      11,
      "catchyYoutubeTitle"
    ],
    "message": "Required"
  }
]
````

I'm running a prompt that is expecting this schema:
```
const IdeasSchema = z.object({
  gameName: z.string(),
  ideas: z.array(z.object({
    catchyYoutubeTitle: z.string(),
    description: z.string(),
    requiredTags: z.array(z.string()),
    optionalTags: z.array(z.string())
  }))
})
```

The prompt contains information about using that: 
````
<snip>
4. Output the ideas like so: 
        NUMBERED_BULLET. **CATCHY YOUTUBE TITLE**
        - Idea Description: IDEA DESCRIPTION
        - Required Tags: REQUIRED TAGS IN LIST FORM
        - Optional Tags: OPTIONAL TAGS IN LIST FORM, IF NO OPTIONAL TAGS, SAY 'None'
    
Remember, you will repeat Step 2 20x, yielding 20 ideas. Once you have completed this step, call the IdeaArray function and pass it *only* these 20 ideas.
````

I see in the code  `private async chatCompletionStandard<T extends z.AnyZodObject>({`
on [line 140](https://github.com/instructor-ai/instructor-js/blob/c205286dccdbc6feacfd2aeeca0e0ba449631a57/src/instructor.ts#L140) `const completion = await this.client.chat.completions.create(resolvedParams)` and it would be helpful to get that text. I'm trying to make a local tweak and I can submit a PR if that makes sense to you all.

**Comment by roodboi** [comment]
good call - we should log out the raw completion debug is on - Ill add a few more in here for the main release - and throw something in the docs for debugging
