### ISSUE TITLE
[Feature Request] Support Anthropic Function Calling

### ISSUE THREAD

**Issue by atbe** [instructor-ai/instructor-js#134]
Placing this request here which I'm sure will be brought up again.

Happy to contribute a PR for this, just let me know what guidelines we should follow.

**Comment by jxnl** [comment]
not sure if @roodboi is working on this

**Comment by murp-2075** [comment]
Until instructor gets Anthropic support, is there another similar library with support? Haiku is far too powerful to ignore right now.

**Comment by nneven** [comment]
bump, would be awesome if we could use Anthropic Claude 3 Opus
