### ISSUE TITLE
Unable to be used with gpt-4-vision 

### ISSUE THREAD

**Issue by AlexXi19** [instructor-ai/instructor-js#142]
message: 'Unrecognized request argument supplied: functions',
    type: 'invalid_request_error',
    param: null,
    code: null

  message: "Invalid parameter: 'response_format' of type 'json_object' is not supported with this model.",
    type: 'invalid_request_error',
    param: 'response_format',
    code: null

tried different modes, but none are working.

**Comment by jxnl** [comment]
use MD_JSON

**Comment by AlexXi19** [comment]
Worked
