### ISSUE TITLE
Unable to use request options with response model enabled

### ISSUE THREAD

**Issue by warlock7** [instructor-ai/instructor-js#151]
Hi,

what I am trying to do: re-use openai client and change its options by passing it in the request options section with `response_model` enabled
unfortunately the TS throws error saying we cant use `response_model`

how to use request options with `response_model` enabled ?

sample code:
```
import { openai } from "../utils/openai";

const instructorJsClient = Instructor({
  client: openai,
  mode: "MD_JSON",
});

const UserSchema = z.object({
  age: z.number().describe("The age of the user"),
  name: z.string(),
});

async function callOpenAiWithInstructor() {
  const response = await instructorJsClient.chat.completions.create(
    {
      messages: [{ role: "user", content: "Jason Liu is 30 years old" }],
      model: "gpt-3.5-turbo",
      response_model: {
        schema: UserSchema,
        name: "User",
      },
    },
    {
      timeout: 30000,
    }
  );

  return response;
}
```

error screenshot:
<img width="891" alt="image" src="https://github.com/instructor-ai/instructor-js/assets/18355407/a8c1c62a-9d81-48f2-9407-6dfcd8f91546">

it works if we not pass the request options (here: `timeout` )

**Comment by RayTCosgrove** [comment]
I am experienceing the same issue

**Comment by roodboi** [comment]
👀
