### ISSUE TITLE
use instruct models?

### ISSUE THREAD

**Issue by dcsan** [instructor-ai/instructor-js#159]
the instruct models seem more suitable for structured responses, 
esp the GPT3.5 is so much cheaper than GPT4 so would be nice to use.
https://community.openai.com/t/instructgpt-vs-gpt-3-5-turbo/434241/2

but they don't support the `chat.completions`

I was wondering how to use with instructor? is there another way to call the `client....` ?

```
const user = await client.chat.completions.create({
  messages: [{ role: "user", content: "Jason Liu is 30 years old" }],
  model: "gpt-3.5-turbo",
  response_model: {
    schema: UserSchema,
    name: "User"
  }
})
```

**Comment by martinamps** [comment]
Instructor only implements `chat.completions` today: https://github.com/instructor-ai/instructor-js/blob/main/src/instructor.ts#L303 

You could use `Mixtral-8x7B-Instruct-v0.1` though -- should perform better & cost less. See [this example](https://github.com/instructor-ai/instructor-js?tab=readme-ov-file#using-different-providers-via-proxy)
