### ISSUE TITLE
[Feature request] Support Groq?

### ISSUE THREAD

**Issue by mikealche** [instructor-ai/instructor-js#170]
Hey there! Amazing library! 

As you've may have heard, Groq is insanely fast compared with OpenAI.

Since they have copied OpenAI's client I assumed this library may work... unfortunately, it doesn't. 

The JSON never gets processed correctly no matter which mode I choose.

**Comment by ionflow** [comment]
Very interested in this as well.

**Comment by RayTCosgrove** [comment]
@mikealche @ionflow Hey, i was successfully able to use groq with the following TS snippet. Does this work for you?:

`import Instructor from "@instructor-ai/instructor";
import { z } from "zod";
import Groq from "groq-sdk";

const groq = new Groq({
  apiKey: process.env.GROQ,
});

const client = Instructor({
  client: groq,
  mode: "TOOLS",
});

const UserSchema = z.object({
  // Description will be used in the prompt
  age: z.number().describe("The age of the user"),
  name: z.string(),
});

// User will be of type z.infer<typeof UserSchema>
const user = await client.chat.completions.create({
  messages: [{ role: "user", content: "Sam Altman is 39 years old" }],
  model: "llama3-70b-8192",
  response_model: {
    schema: UserSchema,
    name: "User",
  },
});

console.log(user);
`

**Comment by andraz** [comment]
Groq is supported and works fine for me. You can also try with my previous (commented out) approach.

Both work ok.

```js
import Instructor from '@instructor-ai/instructor'
import { z } from 'zod'
import Groq from 'groq-sdk'

/*
// import OpenAI from 'openai'
const groq = new OpenAI({
  apiKey: GROQ_API_KEY,
  baseURL: 'https://api.groq.com/openai/v1',
})
*/

const groq = new Groq({
  apiKey: GROQ_API_KEY,
})

const client = Instructor({
  client: groq,
  mode: 'TOOLS',
  debug: true,
})
```

**Comment by roodboi** [comment]
Groq is explicitly supported with light weight validation and tests - but worked out of the box since they use pass through on the oai SDK :)

here is the test
https://github.com/instructor-ai/instructor-js/blob/main/tests/mode.test.ts#L27

posted a little demo here:
https://x.com/dimitrikennedy/status/1781513162589622273
