### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by swyxio** [instructor-ai/instructor-js#187]
could you maybe retry your json.parse call when it fails? this seems like a completely unnecessary self-own... when i have retries left unused

![image](https://github.com/instructor-ai/instructor-js/assets/6764957/cf2ae16d-c0f5-4475-a644-68a3a81c1e47)

**Comment by roodboi** [comment]
{ retryAllErrors: true } will enable retrying errors that are not just schema validation
