### ISSUE TITLE
help wanting: set up mkdocs 

### ISSUE THREAD

**Issue by jxnl** [instructor-ai/instructor-js#24]
https://github.com/jxnl/instructor/blob/main/mkdocs.yml is the python mkdocs, we should set up one for this too.

- [x] set up mkdocs
- [x] set up github pages 
- [x] intro
- [x]  introduction: 
 - [x]  Welcome To Instructor: 'index.md'
    - [x]  Why use Instructor?: 'why.md'
    - [ ]  Help with Instructor: 'help.md'
    - [ ]  Installation: 'installation.md'
    - [ ] Contributing: 'contributing.md'
  -  [x] Tips: 'concepts/prompting.md'

**Comment by liangnuaa** [comment]
Hi Jason, pinged you on twitter, I can help with this, can you add me to contributor list so I can push a draft PR? thanks!
