### ISSUE TITLE
help wanted: Adding foundational testings

### ISSUE THREAD

**Issue by jxnl** [instructor-ai/instructor-js#5]
Looking for some help to setup tests that look like: https://github.com/jxnl/instructor/tree/main/tests/openai

A bonus would be to add circle ci

- [ ] UserExtract Tests
- [ ] List[Properties] tests

**Comment by jxnl** [comment]
importantly just testing that patch works: https://github.com/jxnl/instructor/blob/main/tests/openai/test_patch.py
would be very high impact

**Comment by jxnl** [comment]
ChatGPT suggests

```js
import { OpenAI } from "openai";
import { instructor } from "../../src";
import { z } from "zod";

describe("Client Chat Completions", () => {
  const models = ["gpt-3.5-turbo-1106", "gpt-4-1106-preview"];
  const modes = [
    instructor.Mode.FUNCTIONS,
    instructor.Mode.JSON,
    instructor.Mode.TOOLS,
  ];

  // Create a Cartesian product of models and modes
  const testCases = models.flatMap(model => modes.map(mode => ({ model, mode })));

  test.each(testCases)("should return correct name and age for model %s and mode %s", async ({ model, mode }) => {
    const client = instructor.patch({
      client: new OpenAI(),
      mode: mode,
    });

    const response = await client.chat.completions.create({
      messages: [{ role: "user", content: "Jason Liu is 30 years old" }],
      model: model,
      // @ts-ignore
      response_model: z.object({
        age: z.number(),
        name: z.string().refine(name => name === name.toUpperCase(), {
          message: "name should have uppercase",
        }),
      }),
      max_retries: 3,
    });

    expect(response).toBeDefined();
    expect(response.age).toBe(30);
    expect(response.name).toBe("JASON LIU");
  });
});
```

**Comment by stordahl** [comment]
@jxnl I see core tests have been added - are you interested in getting to 100% coverage? Happy to put up a PR 

![image](https://github.com/jxnl/instructor-js/assets/60861572/6f19790f-8b4f-4da3-b08d-9e152def374e)

**Comment by jxnl** [comment]
> @jxnl I see core tests have been added - are you interested in getting to 100% coverage? Happy to put up a PR
> 
> ![image](https://private-user-images.githubusercontent.com/60861572/293822572-6f19790f-8b4f-4da3-b08d-9e152def374e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNTgyODksIm5iZiI6MTcwNDI1Nzk4OSwicGF0aCI6Ii82MDg2MTU3Mi8yOTM4MjI1NzItNmYxOTc5MGYtOGI0Zi00ZGEzLWIwOGQtOWUxNTJkZWYzNzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA0NTk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5YjRhMzM1NDU5ZmM0MDk1NmU2YjkxMTEyODZmYzEyZjM2OWI1ZmUzODM0YTIzM2NiYTgxYjU1MWIxNmFiMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ot_oW8GFXRD2AaK048EbuAYmJc6mTT987PJKhniUBCI)

would be nice to have some improved coverage and some new badges/ci to show for it!
