### ISSUE TITLE
help wanted: publish on npm, set up releases 

### ISSUE THREAD

**Issue by jxnl** [instructor-ai/instructor-js#7]
if you're able to help up i can give you moderator permissions

**Comment by roodboi** [comment]
the actions to produce release prs, publish and build have been merged in.

The final steps before this can be marked complete I think are:

- [] Choose/confirm availability for npm package name
- [] setup npm org or account (im assuming @jxnl would want to do this to maintain ownership) and add NPM_TOKEN with publish perms to repo env
- [] document changeset workflow - assign owner(s) for publishing PR merging ability
- [] ensure tests/functionality etc are where they should be for a v0 release

**Comment by jxnl** [comment]
Trying to get npm to release instructor package name.

**Comment by ethanleifer** [comment]
Is instructor-js published yet?

**Comment by roodboi** [comment]
@ethanleifer think we are waiting on npm to release "instructor" still
