### ISSUE TITLE
Basic streaming example has type error: Type ... must have a '[Symbol.asyncIterator]()' method that returns an async iterator.

### ISSUE THREAD

**Issue by lawrencecchen** [instructor-ai/instructor-js#95]
[Basic streaming example](https://github.com/instructor-ai/instructor-js/blob/main/examples/extract_user_stream/index.ts) has type error.

Version: 0.0.4

https://stackblitz.com/edit/typescript-13jfod?file=index.ts

<img width="685" alt="Screenshot 2024-01-30 at 3 06 06 AM" src="https://github.com/instructor-ai/instructor-js/assets/54008264/735d2a47-a51e-447d-8f1d-d3887890091b">

Type definitions:
<img width="685" alt="Screenshot 2024-01-30 at 3 09 33 AM" src="https://github.com/instructor-ai/instructor-js/assets/54008264/fec80d95-ad71-47b1-8d11-5f1945d84146">

Not sure why it references OpenAI's type definitions instead of the one defined in `src/instructor.ts`.

**Comment by roodboi** [comment]
hmm yeah - this is a post build thing - if I look at it locally its correct, we even have a test to catch problems with inference - ill dig in a bit

![CleanShot 2024-01-30 at 13 43 07@2x](https://github.com/instructor-ai/instructor-js/assets/344842/4b8a074f-74d3-41c3-a07a-04f99b3a72b3)

**Comment by roodboi** [comment]
k figured it out - https://github.com/instructor-ai/instructor-js/pull/97 - explained what I found in here
